# use for app aes encrypt
app_key: base64:OUM0DBDvyBumCOybh5K7PdRTbmzXGZtp6eagbUjcX1Q=
jwt_secret:
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${mysql_url}:${mysql_port}/${db_name}?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${db_user}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # DDL generation
  jpa:
    show-sql: false
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


