# use for app aes encrypt
app_key: ${app_key}
spring:
  datasource:
    url: jdbc:mysql://${mysql_url}:${mysql_port}/${db_name}?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${db_user}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # DDL generation
  jpa:
    show-sql: false
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
---
jwt:
  secret: ${jwt_secret}
  expired: ${jwt_expried} # second
---
security:
  password-strength: 10


#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


